version: '3.1'

services:

  db:
    image: postgres
    restart: on-failure:5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - 5432:5432

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
